micronaut:
  application:
    name: demo
  security:
    intercept-url-map:
      - pattern: /microstream/**
        http-method: GET
        access:
          - isAnonymous()
netty:
  default:
    allocator:
      max-order: 3



microstream:
  storage:
    main:
      root-class: 'com.example.FruitContainer'
      storage-directory: 'build/fruit-storage'